#!/bin/sh

# This script is a pre-commit hook that runs the code quality checks before
# allowing a commit to be made. If any of the checks fail, the commit is
# aborted and the user is informed of the error.

# TIP: you can enable this hook by running the following command:
#      make enable-pre-commit-hook

if ! make check-format; then
    echo "|"
    echo "|"
    echo "Code quality pre-commit hook error:"
    echo "Black formatting failed! Please fix the errors before committing."
    echo "TIP: you can run \"make format-code\" to try resolving the error automatically."
    exit 1
fi

if ! make check-lint; then
    echo "|"
    echo "|"
    echo "Code quality pre-commit hook error:"
    echo "Flake8 linting failed! Please fix the errors before committing."
    echo "TIP: you can run \"make lint-code\" to try resolving the error automatically."
    exit 1
fi

exit 0
