name: CI

on: [
  workflow_call,
  workflow_dispatch
]

jobs:
  Check-Format:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout to current branch'
        uses: actions/checkout@v3
      - name: 'Run format check'
        run: make check-format-docker

  Check-Linter:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout to current branch'
        uses: actions/checkout@v3
      - name: 'Run lint check'
        run: make check-lint-docker

  Check-Tests:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout to current branch'
        uses: actions/checkout@v3
      - name: 'Run acceptance tests'
        run: make test-app-docker